### ISSUE TITLE
Step 1: User type “agent” to ask for escalation request, you’ll get the following response

### ISSUE THREAD

**Issue by technicalbirdVayuz** [vayuz-botter/issue-tracker#1]
Nothing returned, used wss://web.gateway.staging.botter.live/ && wss://web.gateway.beta.botter.live/

**Comment by AshrafHefny** [comment]
hi @technicalbirdVayuz, 
this is working, and we tried it in our last call!!
are you still facing issue here?

**Comment by technicalbirdVayuz** [comment]
Closing this, its working now
