### ISSUE TITLE
no validation on the mobile number or membership ID number is valid or invalid

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#16]
form screen
1. the mobile number should be a Saudi number
2. membership ID number should be at least 4 digit
https://drive.google.com/file/d/1j8XgP05n0tGZDgFtvJycAqYyvqQ_VTHM/view?usp=sharing

**Comment by technicalbirdVayuz** [comment]
Check Added, 
- Mobile No minimum digit - 12
- Membership Id - Minimum Digit - 4

**Comment by Arushiv13** [comment]
Done

**Comment by abanoubBC** [comment]
mobile number should be Saudi number only 
![WhatsApp Image 2022-01-22 at 9 16 49 PM](https://user-images.githubusercontent.com/96580545/150652604-1d0a7124-b3d3-477e-b899-f922f34017ad.jpeg)

**Comment by technicalbirdVayuz** [comment]
Regex Added, Also, can you change the regex to 
**/^(009665|9665|\+9665|05|5)(5|0|3|6|4|9|1|8|7)([0-9]{7})$/**

For now, I have added it static. Let me know if this can be changed, the current one does not seem to be working

Ref: https://stackoverflow.com/a/53667951/8761336
