### ISSUE TITLE
Please appear all messages info in the centre of the chat without background black as  "Jared joined", "Audio/video call accepted/rejected by Agent", ..etc 

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#19]
Please appear the messages info in the centre of the chat without background black as  "Jared joined", "Audio/video call accepted/rejected by Agent", ..etc 

Steps:

1. open CXI portal
2. open the app
2. fill the form
3. Typing "agent" then submit
4. accept the request from the user on cxi side
5. for example display message info says "Agent joined" on the chat of user (the app)
6. the user asks for an audio/video call and accept
7. display message info  audio/video call accepted
8. the agent rejects the call 
9. display message info say " the agent rejects the call ...."
10. the agent end the chat 
11. display the agent ended the chat

expected result:

1. appear all messages info in the centre of the chat 
2. appear all messages info without background black

actual result 

1. missing  appear all messages info except agent joined only
2. "join agent" displayed in the background black

https://drive.google.com/file/d/1yb50faS_N7X0UDNGPpdVzaq3dqCiIfmn/view?usp=sharing

**Comment by technicalbirdVayuz** [comment]
Following are the events captured
- agent accepts/reject the video call
- agent accepts/reject the audio call
- agent ended the session
- agent name comes when agent joined


For the following events, We would need the CXI DOC
- Agent ends the call after connecting once
- agent decline the request for escalation

Also, In chat history sockets, let us know what needs to be passed so that we can differentiate system messages. Tried changing sender type but it does not works

**Comment by technicalbirdVayuz** [comment]
As discussed,

- Agent ends the call after connecting once - Sorted
- agent decline the request for escalation  - Timeout has to be set from CXI team, Once the timeout is set we can check again

**Comment by abanoubBC** [comment]
it appears well in the align centre during the session but in case clicking on back then continue the conversation all messages info display aligned left
- please appear the message " the audio/video call ended" after the customer or agent ends the call 

![WhatsApp Image 2022-01-22 at 8 27 21 PM](https://user-images.githubusercontent.com/96580545/150651811-6f48d721-1edd-43b3-a0f5-db84f7281aab.jpeg)

![WhatsApp Image 2022-01-22 at 8 27 20 PM](https://user-images.githubusercontent.com/96580545/150651818-bdb9eff6-d44a-4d85-a36a-d2ebf436ab7f.jpeg)

**Comment by technicalbirdVayuz** [comment]
We asked for this in our discussion & mentioned the same here ( https://github.com/vayuz-botter/issue-tracker/issues/20#issuecomment-1015371628) 

We would require an update from your end to close this

**Comment by technicalbirdVayuz** [comment]
As Discussed, we will not be sharing system events  with botter sockets

**Comment by abanoubBC** [comment]
fixed
