### ISSUE TITLE
End the session in case the agent end the conversation to can continue call agent again or browsing rest of the services 

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#20]
Please end the session in case the agent send this message (The system has ended the session due to inactivity) 
and end the session with the display "Chat ended" from the user side
to can continue call agent again or browsing rest of the services 

Steps:

1. open CXI portal
2. open the app
2. fill the form
3. Typing "agent" then submit
4. accept the request from the user on cxi side
5. leave the chat without sending anything for 30 min (a long time)
5. note the agent end the chat 
6. try to send any word "hi" or "text" from the app
7. 
expected result:

1. the conversation ended and display a message "system has ended the session due to inactivity" 
2. display another message that says "The chat ended"
3. the user can continue calling the agent again or browsing the rest of the services 
https://drive.google.com/file/d/1d6EAd07qBlli2dB37Vp0g-jBfQMQERkQ/view?usp=sharing

actual result 

1. No action appears when sending any words in the chat
2. no existing message info to know the chat ended by system
3. the user can not continue calling the agent again or browsing the rest of the services 
https://drive.google.com/file/d/1yb50faS_N7X0UDNGPpdVzaq3dqCiIfmn/view?usp=sharing

**Comment by technicalbirdVayuz** [comment]
Need discussion on Pointer 3. 

For 1 & 2, Time shared

**Comment by technicalbirdVayuz** [comment]
Currently, as discussed it's open. We would need a different key or different values in existing keys

**Comment by Arushiv13** [comment]
Pending. Only 3 is working

**Comment by technicalbirdVayuz** [comment]
@Arushiv13 Please check again & connect in case of not working, I checked again 1 & 2 are working

**Comment by AshrafHefny** [comment]
hi @technicalbirdVayuz 
lets include this point in our call inshallah

**Comment by technicalbirdVayuz** [comment]
Closing this. Feel free to open in case of any issue
