### ISSUE TITLE
the screens audio/video calls do not match the design 

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#21]
the screens audio/video calls do not match the design 
Expect this design
https://drive.google.com/drive/u/3/folders/1HapOyMhT5miFjRM65AI9oTs_ldYKcfXo

Actual design
https://drive.google.com/file/d/1L59lxgyefgwnIkEVt4nyeyLojx8ZXAza/view?usp=sharing

**Comment by technicalbirdVayuz** [comment]
Checked the designs, & also asked for some updates on WhatsApp. 

Sharing the final update here,

- Load Speaker in the Audio Chat
You mentioned you would need it but there is no method available in the SDK, Please contact CXI for this

- Timer
from cordova side, without any logic, when session start timer will start and when session closed timer will disappear (this client side only and not related to history or any other logic) - We have added this

- Profile Image in audio call,
- you have shared this image (https://prod-api.botter.live/uploads/2020-08-10/1597053363.png
), we will check this & update. As the html for this has to come from the methods provided by SDK, We need to check & then we can update

Also, one more the frequency effect while user is speaking, this would not be possible as again this depends on the CXI SDK

@abanoubBC

**Comment by abanoubBC** [comment]
1- missing arrow back in the top left 
2- appearing count of message on chat icon during the call in case a user receives a message from the agent side
actual 
![WhatsApp Image 2022-01-22 at 8 27 18 PM (2)](https://user-images.githubusercontent.com/96580545/150651312-586cc2d7-5f9d-4f04-91f5-61db2f36e62c.jpeg)

expected
https://drive.google.com/drive/u/3/folders/1HapOyMhT5miFjRM65AI9oTs_ldYKcfXo

**Comment by abanoubBC** [comment]
fixed
