### ISSUE TITLE
The user can not send or see the messages during the audio/video calls

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#22]
the user can not send or see the messages during the audio/video calls
Steps:

1. open CXI portal
2. open the app
2. fill the form
3. Typing "agent" then submit
4. accept the request from the user on cxi side
5. ask to an audio/video calls
6. agent accept the call
7. the agent sent a message to the user
8.  

expected result:

1. the user receives the message from the agent 
2. the user can see the message during the call
3. the user can replay the message to the agent 
4. the user can see the count of messages in case the user didn't see the messages
3. 

actual result:
the user can't send any message during the call
https://drive.google.com/file/d/1L59lxgyefgwnIkEVt4nyeyLojx8ZXAza/view?usp=sharing

**Comment by technicalbirdVayuz** [comment]
Solved, instead of count highlighted chat icon

**Comment by Arushiv13** [comment]
Done

**Comment by abanoubBC** [comment]
done

**Comment by abanoubBC** [comment]
fixed
