### ISSUE TITLE
after uploading an image or voice recorder then click the back arrow then click on continue conversation the image appear as code not an image in the chat

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#23]
after uploading an image or voice recorder then click the back arrow then click on continue conversation the image appear as code not an image in the chat

Steps:

1. open the app
2. fill the form
3. click on the + icon
4. upload an image
5. click on the back arrow
6. click on continue conversation
7. 

expected result:
 in every time appear image normal ( after uploading and after continue the conversation)

actual result 
the image appears as code after continuing the conversation as the screen attached
https://drive.google.com/file/d/1qZcK8NUDpDmon-kShRQ0EY1i28fW-ASl/view?usp=sharing

**Comment by Arushiv13** [comment]
Done

**Comment by abanoubBC** [comment]
done

**Comment by abanoubBC** [comment]
fixed
