### ISSUE TITLE
when sending any keywords like "hi, hero, text,..etc" the response duplicate but when clicking on back then continue the conversation the message is a single message

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#24]
when sending any keywords like "hi, hero, text,..etc" the response duplicate but when clicking on back then continue the conversation the message is a single message

Steps:

1. open the app
2. fill the form
4. typing "hero, hi, text" then enter

expected result:
the response one message

actual result
the message is duplicated
https://drive.google.com/file/d/1V3wUZvi31d_DknmOZcTD5-otOxouaQNK/view?usp=sharing
https://drive.google.com/file/d/1z7TrU6742ecKH3HkMFSpCYEcCaA1P72k/view?usp=sharing
https://drive.google.com/file/d/1sTfoTOvrKrHn8GZRd61PMOx-WtfE6v5m/view?usp=sharing

**Comment by technicalbirdVayuz** [comment]
We will share the new build, please check this again, We have resolved this issue in previous builds. 

Also, added version number

**Comment by abanoubBC** [comment]
done
