### ISSUE TITLE
placeholder of text input should be integrated 

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#25]
placeholder of text input and form to start should be integrated 

https://drive.google.com/file/d/13Buk8cr3U_84fKimXudj_InqJT4chvZ2/view?usp=sharing
https://drive.google.com/file/d/1jgRQX1rYJp9gMrTkPAV15soohVeZvxV7/view?usp=sharing

**Comment by technicalbirdVayuz** [comment]
Have used **inputPlaceHolder** key from widget-settings api.

**Comment by Arushiv13** [comment]
Done

**Comment by abanoubBC** [comment]
done
