### ISSUE TITLE
when adding/removing field in the form from the dashboard "https://staging.botter.live"  I have to uninstall the app and install it again to appear the updated changes 

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#26]
when adding/removing field in the form from the dashboard "https://staging.botter.live" 
I have to uninstall the app and install it again to appear the updated changes

**Comment by technicalbirdVayuz** [comment]
Can we have access for the panel? We will try to replicate the case at our end

**Comment by Arushiv13** [comment]
@abanoubBC

**Comment by abanoubBC** [comment]
Hi Vayuz-Botter/Issue-Tracker,
already i added two fields to check and config on them
the form to start chat include these attributes should be congration by
dashboard not static
Full Name | required
Phone Number |  optional
Membership ID Number | required
Email Address | required
test | optional
test 2 | required

User chat placeholder

Write a reply...


*i you need another configuration let me know *

**Comment by abanoubBC** [comment]
still, this issue exists

**Comment by technicalbirdVayuz** [comment]
Keys are mandatory, but in the received responses, no keys are given that's why its not being shown. Can you add key & check again

**Comment by AshrafHefny** [comment]
hi @technicalbirdVayuz 
to get form inputs and configuration [input datatype - validation - label] you need to call API form endpoint as below:- 
https://api.{{env}}.botter.live/widget/data/{{Language}}?bot_id={{Bot_id}}

Then parsing form inputs should be based on data returned from this endpoint to cover the following:-
- list of form inputs 
- text, label per input 
- validation needed on each input 
- error message on each input

**Comment by technicalbirdVayuz** [comment]
This is the response we are getting

```
[
    {
        "errorMessage": "Please enter your full name!",
        "key": "user_name",
        "label": "Full Name",
        "regex": "",
        "required": true,
        "type": "textfield"
    },
    {
        "errorMessage": "Please enter your phone number!",
        "key": "phone_number",
        "label": "Phone Number",
        "regex": "^(((\\u0660\\u0660\\u0669\\u0666\\u0666\\u0665|\\u0669\\u0666\\u0666\\u0665|\\+\\u0669\\u0666\\u0666\\u0665|\\u0660\\u0665|\\u0665)(\\u0665|\\u0660|\\u0663|\\u0666|\\u0664|\\u0669|\\u0661|\\u0668|\\u0667)([\\u0660-\\u0669]{7}))|((009665|9665|\\+9665|05|5)(5|0|3|6|4|9|1|8|7)([0-9]{7})))$",
        "regex_android": "[0-9]+",
        "regex_ios": "[0-9]+",
        "required": true,
        "type": "textfield"
    },
    {
        "errorMessage": "Please enter your membership ID number!",
        "key": "membership_id",
        "label": "Membership ID Number",
        "regex": "^([0-9]{5,10})$",
        "regex_android": "[0-9]+",
        "regex_ios": "[0-9]+",
        "required": true,
        "type": "textfield"
    },
    {
        "errorMessage": "Please enter your email address!",
        "key": "email",
        "label": "Email Address",
        "regex": "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$",
        "regex_android": "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$",
        "regex_ios": "^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$",
        "required": true,
        "type": "textfield"
    },
    {
        "errorMessage": "",
        "key": "",
        "label": "test",
        "multiple": true,
        "options": [
            "test 1",
            "test"
        ],
        "regex": "",
        "regex_android": "",
        "regex_ios": "",
        "required": true,
        "type": "select"
    },
    {
        "errorMessage": "",
        "key": "",
        "label": "test 2",
        "regex": "",
        "regex_android": "",
        "regex_ios": "",
        "required": true,
        "type": "textarea"
    }
]
```

Please note the **key** is empty in the last 2 elements of the array & a key is required in rendering. If you could add the key then it should work.

Also, there are more types in the response compared to what was shared with us initially.

**Comment by technicalbirdVayuz** [comment]
@abanoubBC Please mention all the keys we need to render

**Comment by technicalbirdVayuz** [comment]
@abanoubBC @AshrafHefny Please mention all the unique **type**

**Comment by abanoubBC** [comment]
@technicalbirdVayuz 
![272216156_451858873079325_2192408732756277733_n](https://user-images.githubusercontent.com/96580545/151016978-c4df2121-8ca6-46dd-82ca-52e171877486.png)

**Comment by technicalbirdVayuz** [comment]
@abanoubBC Please add examples for all of them in the response we need to configure them.

**Comment by abanoubBC** [comment]
@technicalbirdVayuz 
I added examples for all types,
please check again

**Comment by technicalbirdVayuz** [comment]
Configured for all. Let us know in case of any issue

**Comment by abanoubBC** [comment]
fixed
