### ISSUE TITLE
when the agent type a message should appear typing card on the user side on chat during the agent is typing a message

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#27]
when the agent type a message should appear typing card on the user side on chat during the agent is typing a message

Steps:

1. open CXI portal
2. open the app
3. fill the form
4. Typing "agent" then submit
5. accept the request from the user on cxi side
6. the agent is typing a message
7. another side (the app should appear the agent is typing ... )

expected result:
the user can know the agent is writing a message during he is typing
actual result:
 no action appears during the agent is writing a message

**Comment by Arushiv13** [comment]
Review Done.

**Comment by abanoubBC** [comment]
done
