### ISSUE TITLE
Step 3: Message sent from plugin not visible in Web

### ISSUE THREAD

**Issue by technicalbirdVayuz** [vayuz-botter/issue-tracker#3]
We are passing the following details in socket.send Function
{
    "type": "cxi_webrtc_message",
    "bot_id": "HtdYuCaNrXuSPpXoiMKT",
    "text": "abcd",
    "user": "random-id-1640171652758",
    "channel": "mobile-android",
    "cxi_webrtc_session_id": "KXHFU38KVVOR5",
    "sender_type": "user"
}

but its not reflected int he web. Sharing the socket object also,  let webSocketURL = "wss://web.gateway.beta.botter.live/"; var socket = new WebSocket(webSocketURL); the flow is correct, but plz make sure you're working on same bot environment -staging- not - bete-, if you still facing issue plz update me to check it  

Update : Environment is staging ( wss://web.gateway.staging.botter.live/) but still its not working

**Comment by AshrafHefny** [comment]
"not reflected int he web", what this means? this is only to update botter, nothing will be returned from socket in this case

**Comment by technicalbirdVayuz** [comment]
Solved
