### ISSUE TITLE
please remove these screens during ask audio/video call

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#30]
please remove these screens during ask audio/video call
![WhatsApp Image 2022-01-22 at 8 27 21 PM (2)](https://user-images.githubusercontent.com/96580545/150671495-103c455e-c527-42f5-8631-6fb731eb8e58.jpeg)
![WhatsApp Image 2022-01-22 at 8 27 20 PM (2)](https://user-images.githubusercontent.com/96580545/150671501-549b2b60-c526-4e32-9aed-af130bb29317.jpeg)

**Comment by technicalbirdVayuz** [comment]
We have added that screen for the following reasons
- whenever you call then there is 2-3 seconds delay in the transition and the video also took time to load that resulting in the second screen (https://user-images.githubusercontent.com/96580545/150671501-549b2b60-c526-4e32-9aed-af130bb29317.jpeg), if we remove this then it will result in bad UX. 

We can modify the screen but removing it is not mandatory

**Comment by technicalbirdVayuz** [comment]
Also, The video is of 35 MB ( https://test.cxinfinity.novelvox.net/errors/CXINIFINITY.mp4) Please compress this if possible

**Comment by AshrafHefny** [comment]
> We have added that screen for the following reasons
> 
> * whenever you call then there is 2-3 seconds delay in the transition and the video also took time to load that resulting in the second screen (https://user-images.githubusercontent.com/96580545/150671501-549b2b60-c526-4e32-9aed-af130bb29317.jpeg), if we remove this then it will result in bad UX.
> 
> We can modify the screen but removing it is not recommended

Hi @technicalbirdVayuz 
having this screen to handle the delay is good move, yet please change this image to something related to our UI, even just a load with our branding colors

**Comment by AshrafHefny** [comment]
> Also, The video is of 35 MB ( https://test.cxinfinity.novelvox.net/errors/CXINIFINITY.mp4) Please compress this if possible

Hi @technicalbirdVayuz 
noted, I will send to CXI to compress this video, yet we work on it as is to handle the case

**Comment by vayuzpriya** [comment]
@AshrafHefny  
Please share UI Changes for the loader.

**Comment by abanoubBC** [comment]
@technicalbirdVayuz 
please change the image after accepting the audio call 
to this screen "https://prod-api.botter.live/uploads/2020-08-10/1597053363.png"
![274027139_481052380163384_4460032138671507210_n (1)](https://user-images.githubusercontent.com/96580545/155106312-325566f7-70b5-4d09-9cb7-93bbb93e3772.jpg)

**Comment by technicalbirdVayuz** [comment]
Yesterday there was some issue we are facing with CXI audio video call.

Today, its working fine https://drive.google.com/file/d/1EIqL2d4e9XBvKw3VBBAfpPCs24nFHUkT/view?usp=sharing

The changes you are mentioning has already been implemented

**Comment by abanoubBC** [comment]
@technicalbirdVayuz still the smae image 
![WhatsApp Image 2022-02-27 at 11 03 49 AM](https://user-images.githubusercontent.com/96580545/155875868-45a07f78-644e-4046-aee1-d2523a3c4a0e.jpeg)

**Comment by abanoubBC** [comment]
@technicalbirdVayuz  still the same image

**Comment by technicalbirdVayuz** [comment]
@abanoubBC  Please share the screen recording & plugin version

**Comment by abanoubBC** [comment]
done
