### ISSUE TITLE
please remove the timer (15 sec) when asking the agent 

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#34]

**Comment by technicalbirdVayuz** [comment]
@abanoubBC Let us know when you received timeout configuration from CXI Team, We will iterate it

**Comment by abanoubBC** [comment]
@technicalbirdVayuz 
CXI configured it for 2 minutes

**Comment by technicalbirdVayuz** [comment]
We were not able to test it. As CXI panel was down

**Comment by abanoubBC** [comment]
@technicalbirdVayuz  please remove the time because happened an issue
when asking for an escalation and the time ended from the customer side then the agent accept the request. the session still is opening and the agent can send messages but the user can't send  messages to the agent
![WhatsApp Image 2022-02-22 at 10 48 37 AM](https://user-images.githubusercontent.com/96580545/155096892-c9e10902-aa00-4ac2-8252-82dba27aa9d2.jpeg)
![WhatsApp Image 2022-02-22 at 10 48 37 AM (1)](https://user-images.githubusercontent.com/96580545/155096903-cccddd52-69a7-43d1-9599-611af0824b46.jpeg)
![273924197_678653496816930_1891058997996036538_n](https://user-images.githubusercontent.com/96580545/155096957-800addd3-ee59-473c-8a57-5e7b97331779.png)

**Comment by technicalbirdVayuz** [comment]
The timeout needs to be discussed for this. We will discuss this in the call today

**Comment by technicalbirdVayuz** [comment]
Its changed to 5 minutes

**Comment by abanoubBC** [comment]
@technicalbirdVayuz 
after changing the timer to 5 min occurred issue, 
when the timer ended, this statement has been repeated " agent is not available" many times without stopping however I clicked on the back arrow then the continue conversation but the statement still display 

https://user-images.githubusercontent.com/96580545/156404294-adfe054f-d3be-42ea-907f-a27857a1343c.mp4


https://user-images.githubusercontent.com/96580545/156404336-ec6d1d40-3657-41b2-b88e-9afe45627be8.mp4

**Comment by technicalbirdVayuz** [comment]
Can you share the use case for this or a screen recording if possible? We have checked the case but its not happening at our end

**Comment by technicalbirdVayuz** [comment]
Moved to #44
