### ISSUE TITLE
iOS |  header of chat screen is cutting and can not click on the back

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#37]
1- header of chat is cutting 
2- can not click on the back

![WhatsApp Image 2022-01-29 at 3 39 28 PM](https://user-images.githubusercontent.com/96580545/151663316-06f7c9c9-7e39-4172-a086-2bb07b80621c.jpeg)

**Comment by rohitrvayuz** [comment]
This is fixed. Please check on TestFlight Version 1.0.0 Build # 16

**Comment by abanoubBC** [comment]
@technicalbirdVayuz 
the issue is fixed, but apparently another issue 
the arrow back, all text and icon images should be space on the right side as a screen attached 
![274301296_683129463005774_5771833264659191008_n](https://user-images.githubusercontent.com/96580545/155097638-82588921-ebef-4393-9c0e-dab2ebfa2738.jpg)

**Comment by vayuzpriya** [comment]
for-ios is mention in every new class. Pls search when you added ios Class for IOS build.

**Comment by technicalbirdVayuz** [comment]
ok, have done the needful changes

**Comment by abanoubBC** [comment]
@technicalbirdVayuz 
still, the same issue exists "the arrow back, all text and icon images should be space on the right side as a screen attached"
![274754497_1273959209682090_7425438956493851009_n](https://user-images.githubusercontent.com/96580545/156405313-e8ba0c0d-d345-49c1-9266-bc2e712cc714.jpg)

**Comment by technicalbirdVayuz** [comment]
Fixed in the last shared  build

**Comment by abanoubBC** [comment]
fixed
