### ISSUE TITLE
attachment is not working when the agent send attachment to user and the attachment did not appear in user side

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#39]
attachment is not working when the agent send an attachment to the user and the attachment did not appear on the user side

steps:

1. fill the form to start the chat
2. type "agent" for escalation
3. the agent accepts the request 
4. the agent send an attachment 
5. the user  didn't receive the attachment 

Expected Result:
the user receives the attachment and can see it

Actual Result:
the user didn't receive the attachment as the screen attached 
![WhatsApp Image 2022-02-22 at 11 28 28 AM (1)](https://user-images.githubusercontent.com/96580545/155103143-40a08a36-4c36-409d-ae45-95343a462b43.jpeg)
![WhatsApp Image 2022-02-22 at 11 28 28 AM](https://user-images.githubusercontent.com/96580545/155103152-03ed0e96-d90e-4c0a-afbb-e2cebcd8f370.jpeg)

**Comment by technicalbirdVayuz** [comment]
Fixed,

**Comment by technicalbirdVayuz** [comment]
Recording files not getting uploaded, only images are getting uploaded. Need to check with CXI

**Comment by technicalbirdVayuz** [comment]
![image](https://user-images.githubusercontent.com/18699624/155469835-02af3b42-b22e-4302-915a-c4b7cf553c8a.png)
![image](https://user-images.githubusercontent.com/18699624/155469883-da4bc2e9-61ac-423d-8c7b-6d5310bd6118.png)

**Comment by technicalbirdVayuz** [comment]
`  var form = new FormData();
    if (fileType == "file") {
      $(".myAlert-message").text("Uploading image");
    } else {
      $(".myAlert-message").text("Uploading file");
    }
    if (Utils.isAgentSessionActive()) {
      form.append("userPhoto", file, name);
    } else {
      form.append("file", file, name);
    }
    var settings = {
      url: "https://uploads.staging.botter.live/api/file/upload",
      method: "POST",
      timeout: 0,
      headers: {
        Accept: "application/json",
      },
      processData: false,
      mimeType: "multipart/form-data",
      contentType: false,
      data: form,
    };
    $("#myAlert").addClass("show");
    if (Utils.isAgentSessionActive()) {
      settings.url =
        "https://cxi.novelvox.net/fileoperation/upload";
    }
  
    $(document).ajaxError(function (evt, jqXHR, settings, err) {
      $(".myAlert-message").text("Something went wrong!");
      setTimeout(function(){
        $("#myAlert").removeClass("show");
      },2000);
    });
    var response = await $.ajax(settings).then();
    $("#myAlert").removeClass("show");
    return response;`

**Comment by abanoubBC** [comment]
@technicalbirdVayuz images are working well, but another file (word, pdf, voice note...) are not working

**Comment by technicalbirdVayuz** [comment]
https://user-images.githubusercontent.com/18699624/156513630-5cd62e4b-9e22-4596-9438-8745760c487a.mp4

**Comment by technicalbirdVayuz** [comment]
Sharing the accepted file extension: ".jpg", ".jpeg", ".pdf", ".png", ".mp3"

& For Audio not working, we have shared the concern with CXI team. Will update once received update

**Comment by technicalbirdVayuz** [comment]
No its still not working, We are having discussion with CXI team over emails

**Comment by abanoubBC** [comment]
duplicate #42
