### ISSUE TITLE
iOS | during the session with the agent this statement has been repeated " agent is not available" many times without stopping however I clicked on the back arrow then the continue conversation but the statement still display

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#44]
iOS | during the session with the agent this statement has been repeated " agent is not available" many times without stopping however I clicked on the back arrow then the continue conversation but the statement still display I have to uninstall the app then reinstall again 

Steps:

1. open CXI portal
2. open the app
3. fill out the form
4. Typing "agent" then submit
5. accept the request from the user on cxi side 
6. continue the conversation normal with the agent 
7. a note is displayed this statement has been repeated " agent is not available" many times 

Expected Result:
can continue the conversation normal with the agent

Actual Result
a note is displayed this statement has been repeated " agent is not available" many times 
![274660022_1473588429705644_7188737370221188501_n](https://user-images.githubusercontent.com/96580545/156411733-3cfe5a39-4d9a-4eb4-8b34-5f2020900069.jpg)

**Comment by technicalbirdVayuz** [comment]
Can you share the use case for this or a screen recording if possible? We have checked the case but its not happening at our end

Duplicate #34

**Comment by abanoubBC** [comment]
@technicalbirdVayuz  
video for this issue 

https://user-images.githubusercontent.com/96580545/157005031-c95580e4-e72e-4e3e-9993-22c6d4a433d9.mp4


https://user-images.githubusercontent.com/96580545/157005043-88133aab-fd69-427d-98ac-58459056113b.mp4

**Comment by abanoubBC** [comment]
fixed
