### ISSUE TITLE
iOS | if the agent sends an image, the user side received it but a part of the image appears only. please, display the whole image

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#45]
iOS | if the agent sends an image, the user side received it but a part of the image appears only. please, display the whole image

Steps:

1. open CXI portal
2. open the app
3. fill out the form
4. Typing "agent" then submit
5. accept the request from the user on cxi side
6. the agent send an image 
7. the user receives the image 

Expected Result:
the whole image appear without scroll
Actual Result
a part of the image appears only I have to scroll up to see the whole image 

![274849070_670067460971093_8488305886317638362_n](https://user-images.githubusercontent.com/96580545/156413307-fa1b8b6c-4959-4474-acda-3b329e563f50.jpg)

**Comment by rohitrvayuz** [comment]
This is done

**Comment by technicalbirdVayuz** [comment]
Fixed in the last shared build

**Comment by abanoubBC** [comment]
fixed
