### ISSUE TITLE
iOS | the audio/video call screens have not matched the design 

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#46]
iOS | the audio/video call screens have not matched the design 
![274701091_492627612371225_8470845531358578180_n](https://user-images.githubusercontent.com/96580545/156415132-2ca548a1-455a-44e6-a129-259b0bc5cc8a.jpg)
![274840146_2228070930675005_3108634807765847031_n](https://user-images.githubusercontent.com/96580545/156415140-8453c07b-1159-4878-a667-261c11113a75.jpg)

**Comment by technicalbirdVayuz** [comment]
Duplicate #47
