### ISSUE TITLE
please configure the selected field (there is multi select and another single select) in the form 

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#49]
the response is 
**Cuntery field**
{
                "errorMessage": "Please select your Country !",
                "key": "select_country",
                "label": "Cuntery",
                **"multiple": false,**
                "options": [
                    "Egypt",
                    "Saudi Arabia",
                    "India"
                ],
                "regex": "",
                "regex_android": "",
                "regex_ios": "",
                "required": true,
                **"type": "select"**
            },
**hobbies filed**
 {
                "errorMessage": "",
                "key": "hobbies",
                "label": "hobbies",
                **"multiple": true,**
                "options": [
                    "football",
                    "reading",
                    "music"
                ],
                "regex": "",
                "regex_android": "",
                "regex_ios": "",
                "required": false,
                **"type": "select"**
            }

excepted 

1. the user can select  a country only
2. the user can select multi hobbies

Actual 
1. the user can select  multi countries although there is an attribute  **"multiple": false,**
2. the user can select multi hobbies

![275293719_1077722826451320_7514202545733749691_n](https://user-images.githubusercontent.com/96580545/157645353-434e22cf-8517-45e7-99c0-62fb8c0c968f.jpg)

![275550397_2200678826751580_250444931873138574_n](https://user-images.githubusercontent.com/96580545/157645363-f1e61813-89d7-4ed9-808b-1840a8f8d9e2.jpg)

**Comment by abanoubBC** [comment]
the issue was fixed but after selecting items, it displays the colour of the selected item was not readable as the screen attached 
![Screenshot_٢٠٢٢٠٣١٣-١٢٢٦٣٩](https://user-images.githubusercontent.com/96580545/158055548-15a55618-d635-4d54-9bef-256830b879e5.png)

**Comment by abanoubBC** [comment]
the issue is not fixed on iOS version 1.0.0 (20)  1.9

https://user-images.githubusercontent.com/96580545/158064984-f31e8c50-cda4-493e-ac92-9bb5f7741224.mp4

**Comment by Arushiv13** [comment]
@abanoubBC this is the default feature of the bottom sheet, on multiple selection (let's say for more than 5 fields - the UI will not look good), so keeping the no. of items only here. The user can see the list by clicking the field

**Comment by abanoubBC** [comment]
@Arushiv13 this issue still is not fixed on iOS 
the user can select multi countries although there is an attribute "multiple": false,
the user can select multi hobbies

https://user-images.githubusercontent.com/96580545/158166501-e1d354a0-45ef-4bd7-8235-0211f08a2f18.mp4

**Comment by Arushiv13** [comment]
@abanoubBC  it's fixed now, check in nect 30 minutes.
