### ISSUE TITLE
iOS | header of chat screen is cutting and can not click on the back

### ISSUE THREAD

**Issue by abanoubBC** [vayuz-botter/issue-tracker#50]
1- header of chat is cutting
2- can not click on the back
![IMG_٢٠٢٢٠٣١٣_١٦٤٨٤٢_2](https://user-images.githubusercontent.com/96580545/158065434-5982e59d-9c74-45d8-8dfb-0d9b59423e10.jpg)

**Comment by Arushiv13** [comment]
Fixed @abanoubBC

**Comment by abanoubBC** [comment]
done
