### ISSUE TITLE
Uploading media/images not getting downloaded from web

### ISSUE THREAD

**Issue by technicalbirdVayuz** [vayuz-botter/issue-tracker#7]
We need to crosscheck the parameters

**Comment by AshrafHefny** [comment]
hi @technicalbirdVayuz, 
what is the issuer here?
what is the request you send and what is the resposne?

**Comment by technicalbirdVayuz** [comment]
@AshrafHefny 

Pls check

{
	"brokerType": "WEB_SOCKET",
	"sender": "Ankit",
	"messageType": "MESSAGE_SEND",
	"messageKey": "KXQ297XDETA0O",
	"data": {
		"sessionId": "KXQ1R73FTGWT9",
		"message": {
			"chatMessage": "4_Unknown.png",
			"isSenderAgent": false,
			"senderId": "user_id_1640624745343",
			"senderName": "Ankit",
			"senderType": "Customer",
			"sentDateTime": "2021-12-28T12:03:28.993Z",
			"type": "file",
			"fileName": "4_Unknown.png",
			"size": 0
		}
	},
	"timestamp": 1640693008993
}

**Comment by technicalbirdVayuz** [comment]
@AshrafHefny  We debug this at our end, 

From CXI Panel, they are uploading the file at this URL:: https://test.cxinfinity.novelvox.net/fileoperation/upload

While we are using this URL: https://uploads.staging.botter.live/api/file/upload  to upload the file

Please provide Postman collection for CXI PAnel URL so that we can upload & access from the same location & this will also solve the issue as well

**Comment by nezamy** [comment]
Hello @technicalbirdVayuz,

After Upload the file to `/fileoperation/upload`
store the file name from response
`let fileName = response.data.fileName` and send file size correctly

Example
```js
let formObject = new FormData()
const file =  event.target.files[0]
formObject.append("userPhoto", file, file.name)
 //then  send the file to `post('/fileoperation/upload', formObject)`
let fileName = response.data.fileName
      
const message = {
    "chatMessage": fileName,
    "isSenderAgent": false,
    "senderId": "user_id_1640624745343", // Interaction id
    "senderName": "Ankit",
    "senderType": "Customer",
    "sentDateTime": "2021-12-28T12:03:28.993Z",
    "type": "file",
    "fileName": fileName, //from response
    "size": file.size // get file size 
}

```

**Comment by technicalbirdVayuz** [comment]
can you share the complete URL in the POST method?

**Comment by nezamy** [comment]
Same URL `https://test.cxinfinity.novelvox.net/fileoperation/upload`
You need to check if you are connected to the CXI agent you will use this link `https://test.cxinfinity.novelvox.net/fileoperation/upload` 

If not. you will send the file normally to `https://uploads.staging.botter.live/api/file/upload`

**Comment by technicalbirdVayuz** [comment]
Regarding Botter file Upload URL(https://uploads.staging.botter.live/api/file/upload),  
This is the response, when we upload a file
{"code":201,"message":"File uploaded successfully!","name":"2021-12-30/1200px-Image_created_with_a_mobile_phone.png","url":"https://botter-stg.fra1.digitaloceanspaces.com/2021-12-30/1200px-Image_created_with_a_mobile_phone.png","type":"image"}

It does not have fileName, only has a **name**. Please confirm

**Comment by technicalbirdVayuz** [comment]
Regarding CXI upload, After uploading image is visible & can be downloaded from the panel but in the local development, its not being shown


Getting 502 Proxy Error

**Comment by technicalbirdVayuz** [comment]
> Regarding CXI upload, After uploading image is visible & can be downloaded from the panel but in the local development, its not being shown
> 
> Getting 502 Proxy Error

For this, we have handled it using native file object Apis (using file object from local), we can discuss if required

Also, API returns a 500 Error code in case of uploading MPEG (audio file). Please provide the key for audio file also

**Comment by nezamy** [comment]
> It does not have fileName, only has a **name**. Please confirm
Yes, I mean CXI only return `fileName`


> Regarding CXI upload, After uploading image is visible & can be downloaded from the panel but in the local development, its not being shown
> 
> Getting 502 Proxy Error

`https://test.cxinfinity.novelvox.net/fileoperation/download/${message.message.fileName}`
`message.message.fileName` coms from **`onMessageReceive`** event (CXI websocket)

You can do something like this
```js
let msg = message.message
let fileName = msg.fileName
if (msg.type == 'file') {
    let fileExt = fileName.split('.').pop()
    let imagesExt = ['jpg', 'jpeg', 'png', 'gif']
    let fileType =  imagesExt.includes(fileExt) ? 'image' : 'attachment'
    let fileUrl = `https://test.cxinfinity.novelvox.net/fileoperation/download/${fileName}`
}
else if (msg.type == 'audio') {
    let fileExt = fileName.split('.').pop()
    let audioExt = ['mp3', 'wav'] // supported extensions
    let fileType =  audioExt.includes(fileExt) ? 'audio' : 'attachment'
    let fileUrl = `https://test.cxinfinity.novelvox.net/fileoperation/download/${fileName}`
}

```

**Comment by technicalbirdVayuz** [comment]
@AshrafHefny Issue is while uploading the attachment, showcasing audio is not the issue

**Comment by nezamy** [comment]
['mp3', 'wav'] // supported extensions

**Comment by technicalbirdVayuz** [comment]
Thanks, it works!
